apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.userService.service.name }}
spec:
  selector:
    app: {{ .Values.services.userService.service.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.services.userService.service.port }}
  type: ClusterIP
