name: CI/CD Pipeline

on:
  push:
    branches: [master]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push user-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./microservices/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service

      - name: Build and push salle-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/salle-service ./microservices/salle-service
          docker push ${{ secrets.DOCKER_USERNAME }}/salle-service

      - name: Build and push reservation-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-service ./microservices/reservation-service
          docker push ${{ secrets.DOCKER_USERNAME }}/reservation-service

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: 'v3.17.3'  # version que tu veux utiliser, assure-toi que c'est compatible avec ton projet

      - name: Configure Kubernetes credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.K8S_USERNAME }}  # Ajouter ces secrets dans GitHub
          password: ${{ secrets.K8S_PASSWORD }}

      - name: Helm upgrade/install salle-reservation
        run: |
          helm upgrade --install salle-reservation ./helm-chart \
            --set image.repository=${{ secrets.DOCKER_USERNAME }} \
            --set image.tag=latest \
            --namespace default --create-namespace

      - name: Clean up
        run: |
          kubectl get pods  # optionnel, pour vérifier que les pods sont bien en place
